clients/java: describe job worker polling and backoff
camunda-cloud/camunda-cloud-documentation pull request #185
Opened 2021-02-24 14:34 UTC by korthout

Adds a description of the java client's job worker polling behaviour and how to configure its backoff strategy.

closes #183

2021-02-25 10:04 UTC, npepinpe requested changes
I would expand a bit on how the job worker polling mechanism work. I don't think it's clear from a user point of view.

- Does it start polling immediately on creation?
- When does it poll again? How often does it poll? What's the impact on my cluster and why is backoff necessary?
- How are jobs processed? What kind of executor would I want to use? (I realize this is a little out of scope though, so feel free to create a follow up issue)

2021-02-25 10:04 UTC, npepinpe commented on docs/product-manuals/clients/java-client/job-worker.md
> +- polls for jobs before it runs out
Before it runs out...of jobs? ...on its family after going for a pack of cigarette at the corner store? :thinking:

2021-02-25 10:04 UTC, npepinpe commented on docs/product-manuals/clients/java-client/job-worker.md
> +When a poll fails with an error response: the job worker waits for some time, afterwhich it polls again for available jobs.
```suggestion
When a poll fails with an error response: the job worker waits for some time, after which it polls again for available jobs.
```

2021-03-04 18:24 UTC, korthout commented
@npepinpe Sorry for the late reply, but I've applied your review hints. I've also tried to use the style recommended by the [technical writing cheatsheet](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/howtos/technical-writing-cheatsheet.md). Please have a look

2021-03-04 18:35 UTC, akeller commented
Thank you for using the style guide cheatsheet! I can review for style 🙂

2021-03-04 21:58 UTC, akeller requested changes
Just a couple capitalization items from a style guide perspective.

2021-03-04 21:58 UTC, akeller commented on docs/product-manuals/clients/java-client/get-started.md
> +- Learn more about the java client's [job worker](job-worker.md)
```suggestion
- Learn more about the Java client's [job worker](job-worker.md)
```

2021-03-04 21:58 UTC, akeller commented on docs/product-manuals/clients/java-client/index.md
> +- [Job worker](job-worker.md) - Introduction to the java client's job worker
```suggestion
- [Job worker](job-worker.md) - Introduction to the Java client's job worker
```

2021-03-04 21:58 UTC, akeller commented on docs/product-manuals/clients/java-client/index.md
>  - [Logging](logging.md) - Introduction on how to configure logging for Zeebe Client
```suggestion
- [Logging](logging.md) - Introduction on how to configure logging for Zeebe client
```

2021-03-04 21:58 UTC, akeller commented on docs/product-manuals/clients/java-client/job-worker.md
> +## Related Resources
```suggestion
## Related resources
```

2021-03-04 21:58 UTC, akeller commented on docs/product-manuals/clients/java-client/job-worker.md
> +## The java client's job worker
```suggestion
## The Java client's job worker

The Java client provides a job worker that takes care of polling for available jobs and allows you to focus on writing code to handle the activated jobs.
```

2021-03-05 15:10 UTC, npepinpe approved these changes
Looks good from my side :+1:

2021-03-05 15:35 UTC, korthout commented
@akeller thanks for the review, I've made the requested changes. Please have another look.

PS: These changes are part of the upcoming zeebe release. How do we make sure this documentation is not published before the release? Should we keep the PR from being merged, do we have some form of marking the changes as related to a next release or do we just wait with deploying the next version of the documentation until the next release is ready?

2021-03-05 16:02 UTC, akeller commented
We have a branch for `release_0_27` that we've been using for the next Zeebe release, but I mistakenly thought it was going out this month so we have a bit of a mess PR wise right now 🙂 

What release is this for @korthout?

2021-03-05 16:18 UTC, korthout commented
@akeller the next release is 1.0.0 (there is no 0.27 planned afaik), but I can rebase this on that branch if that's the correct way :) Please let me know what you'd like me to do

2021-03-05 18:04 UTC, akeller commented
> @akeller the next release is 1.0.0 (there is no 0.27 planned afaik), but I can rebase this on that branch if that's the correct way (that's no effort at all) :) Please let me know what you'd like me to do

Do that please. Thank you so much! Hopefully the following release is a little more streamlined 😅

2021-03-05 18:06 UTC, akeller reviewed
Looks good from a style guide perspective!

Note - this is just a comment and not an approval in case the approval triggers an auto-merge (which we don't want).

2021-03-05 18:47 UTC, korthout commented
@akeller I've rebased and changed the target for this PR (now pointing to `release_0_27`). Please approve and merge :)

2021-03-05 18:54 UTC, akeller approved these changes

2021-03-05 18:54 UTC, merged

2021-03-05 18:55 UTC, akeller commented
Happy weekend @korthout!