Added alerts documentation
camunda-cloud/camunda-cloud-documentation pull request #211
Opened 2021-04-19 11:02 UTC by ColRad

2021-04-19 11:06 UTC, ultraschuppi commented on docs/product-manuals/cloud-console/manage-clusters/manage-alerts.md
> +To create a `Webhook` alert, you need to provide a valid webhook url that excepts `POST` requests.
and HEAD right?

2021-04-19 11:49 UTC, ColRad commented on docs/product-manuals/cloud-console/manage-clusters/manage-alerts.md
> +To create a `Webhook` alert, you need to provide a valid webhook url that excepts `POST` requests.
well if it accepts POST it accepts HEAD

2021-04-19 11:51 UTC, ultraschuppi commented
thanks @ColRad 
@akeller wanna have a look over it as well? will get merged in 2nd week of march

2021-04-19 11:51 UTC, ultraschuppi approved these changes

2021-04-19 14:43 UTC, akeller commented
> thanks @ColRad
> @akeller wanna have a look over it as well? will get merged in 2nd week of march

2nd week of May? 😄

2021-04-19 15:08 UTC, ultraschuppi commented
> 2nd week of May?

oh dear... yes ;)

2021-04-19 15:26 UTC, ultraschuppi commented
@ColRad i think the images should rather reside in `product-manuals/cloud-console/img`, but since they are having a few pixels of decorations anyway - what about i redo them? ;)

2021-04-20 01:13 UTC, akeller commented
Is this merging into `master`?  If so, please remove references to "workflow". Process -> workflow changes are already staged in `release_0_27` including the variables names for the code snippet.

"Alerts" should be lower case for all references except when quoting the UI.

2021-04-20 06:28 UTC, ultraschuppi commented
> Is this merging into `master`? If so, please remove references to "workflow". Process -> workflow changes are already staged in `release_0_27` including the variables names for the code snippet.

we will just merge this into master as soon as the new release hits the stage (and afterwards cherrypick the mergecommit to the corresponding RB)

> 
> "Alerts" should be lower case for all references except when quoting the UI.

thanks! @ColRad made the corresponding changes

2021-04-22 01:53 UTC, akeller requested changes
Small typo, otherwise this looks magnificent! Thank you both!

2021-04-22 01:53 UTC, akeller commented on docs/product-manuals/cloud-console/introduction.md
> +- [manage Alerts](./manage-clusters/manage-alerts.md) to get notified when workflow error occur,
lowercase "alerts"

2021-05-04 16:57 UTC, akeller reviewed
This is asking me for another review, so here it is! This looks good.

2021-05-07 07:28 UTC, urbanisierung commented
replaced by https://github.com/camunda-cloud/camunda-cloud-documentation/pull/233

2021-05-07 07:28 UTC, closed without merging

2021-05-07 07:28 UTC, ultraschuppi commented
replaced by #233