1.0.0-get-started
camunda-cloud/camunda-cloud-documentation pull request #227
Opened 2021-05-05 21:03 UTC by jwulf

* Remove languages other than Node.js and Java. 
* Update Node.js to 1.0.0 API.
* Remove video links.
* Java example still to come in another PR.

2021-05-06 20:41 UTC, akeller requested changes

2021-05-06 20:41 UTC, akeller commented on docs/guides/setting-up-development-project.md
> +- Open Zeebe Modeler and create a new BPMN Diagram.
Sorry I missed this earlier, can you please modify this to link the Camunda Modeler and working with Camunda Modeler instead? Thanks!

2021-05-07 17:58 UTC, akeller commented
Please rebase when you get a chance, and then this looks good to go @jwulf!

2021-06-23 02:56 UTC, jwulf commented
Closing this for now. Will circle back in Q3.

2021-06-23 02:56 UTC, closed without merging