docs(clients/java): Dead links in docs (#258)
camunda-cloud/camunda-cloud-documentation pull request #262
Opened 2021-05-21 14:37 UTC by akeller

Closes #258.

2021-05-25 09:17 UTC, korthout requested changes
Thanks for these changes, but it does not close the issue yet because not all cases are updated:

Try running `find ./docs -type f -name '*.md' | xargs egrep -i 'java/io/zeebe'` or `ack 'java/io/zeebe' ./docs` to find remaining cases. 

I've saw that you also started updating the zeebe-io organisation references to camunda-cloud. I've provided some extra ones, but there are still quite some more. Try `find ./docs -type f -name '*.md' | xargs egrep -i 'zeebe-io/zeebe/'` or `ack 'zeebe-io/zeebe/' ./docs` to find them.

2021-05-25 09:17 UTC, korthout commented on docs/product-manuals/clients/java-client/job-worker.md
> +You can replace it using the `.backoffSupplier()` method on the [`JobWorkerBuilder`](https://github.com/zeebe-io/zeebe/blob/develop/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/JobWo
```suggestion
The retry delay (i.e. the time the job worker waits after an error before the next poll for new jobs) is provided by the [`BackoffSupplier`](https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/BackoffSupplier.java).
You can replace it using the `.backoffSupplier()` method on the [`JobWorkerBuilder`](https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/JobWorkerBuilderStep1.java).
```

2021-05-25 09:17 UTC, korthout commented on docs/product-manuals/clients/java-client-examples/job-worker-open.md
> +[Source on github](https://github.com/zeebe-io/zeebe/tree/develop/samples/src/main/java/io/camunda/zeebe/example/job/JobWorkerCreator.java)
```suggestion
[Source on github](https://github.com/camunda-cloud/zeebe/tree/develop/samples/src/main/java/io/camunda/zeebe/example/job/JobWorkerCreator.java)
```

2021-05-26 20:53 UTC, akeller commented
Oh! You are totally right. I wasn't paying attention to the URLs, I was just checking whether the link 404'd and it looks like I was redirected and didn't notice 😅 .

2021-05-27 12:47 UTC, korthout commented
Sure, no problem. Just let me know when you want me to take another look 👍

2021-05-28 16:48 UTC, korthout commented
@akeller I think so, but I'm not entirely sure. @npepinpe Did the go import statements change as well with the package renamings?

2021-05-28 16:49 UTC, npepinpe commented
Yes, they also changed, though note that the old ones aren't dead per se but will be redirected by Github.

2021-05-28 18:42 UTC, akeller commented
I'll leave those alone then, thank you both!

2021-05-28 19:23 UTC, akeller commented
I additionally updated links moved to the Community Hub like zeebe-simple-monitor.

I also updated links to raw files, like the gRPC proto buffer file - https://raw.githubusercontent.com/camunda-cloud/zeebe/develop/gateway-protocol/src/main/proto/gateway.proto

Did the inviter link change for Slack? It's still functioning as https://zeebe-slack-invite.herokuapp.com/.

Other than that, I tried to confirm the changes resolved to working URLs. Occasionally there are still some redirects, particularly when walking the directories in GitHub.

2021-06-02 09:21 UTC, korthout approved these changes
Thanks for the changes @akeller 🙇 

This LGTM 👏 

>Did the inviter link change for Slack? It's still functioning as https://zeebe-slack-invite.herokuapp.com/.

AFAIK, this did not change, but it might be a good idea to align naming in the future. Does not need to be part of this changeset.

> Other than that, I tried to confirm the changes resolved to working URLs. Occasionally there are still some redirects, particularly when walking the directories in GitHub.

These redirects are likely due to incorrect usage of `tree`/`blob` in the url: https://stackoverflow.com/a/61959710/3442860. This is nothing bad because GitHub handles these for us, so let's leave this out of the scope of this changeset.

2021-06-02 13:51 UTC, merged