Reorganise Tasklist docs and add Tasklist API tutorial
camunda-cloud/camunda-cloud-documentation pull request #368
Opened 2021-09-22 07:44 UTC by vsgoulart

2021-09-27 08:50 UTC, menski submitted a review, later dismissed
Looks good to me, I just skimmed through and didn't followed the tutorial

2021-10-04 13:00 UTC, akeller requested changes
Just a couple things, nothing major.

2021-10-04 14:02 UTC, vsgoulart commented on docs/components/tasklist/introduction.md
> +Tasklist is a tool to work with [user tasks](https://docs.camunda.org/manual/7.8/reference/bpmn20/tasks/user-task/) in Zeebe. It provides a GraphQL API which you can use to build your own application
At the time I think we didn't have this on the Camunda Cloud docs, so Ralf just linked to the CamBPM docs

2021-10-04 14:58 UTC, akeller approved these changes

2021-10-04 17:29 UTC, merged