Updated link to maintained/default docker-compose file
camunda-cloud/camunda-cloud-documentation pull request #432
Opened 2021-11-04 08:05 UTC by berndruecker

Looking at the installation docs we are currently discussion, I recognized that the docs point to the community extension around docker-compose, which is quite outdated at the moment (old Zeebe versions, no tasklist, ...).

At the same time, the Zeebe team maintains one docker-compose file always using the latest version: https://github.com/camunda-cloud/camunda-cloud-get-started/blob/master/docker-compose.yaml - so we should simply point to this one instead.

2021-11-08 20:30 UTC, akeller commented
@menski does this sound good to you?

2021-11-09 15:09 UTC, menski requested changes
Thanks Bernd, I liked it. Let's just fix the tasklist port

2021-11-09 15:09 UTC, menski commented on docs/self-managed/zeebe-deployment/docker/install.md
> +- [`8081`](http://localhost:8080/): Tasklist
```suggestion
- [`8081`](http://localhost:8081/): Tasklist
```

2021-11-09 22:17 UTC, akeller commented
Committed your suggestion @menski. Going to go ahead and merge this in! Thank you!

2021-11-09 22:18 UTC, merged

2021-11-10 12:20 UTC, berndruecker commented
Great - thanks everybody 👍