Add FAQ section for Tasklist
camunda-cloud/camunda-cloud-documentation pull request #439
Opened 2021-11-11 20:44 UTC by vsgoulart

Closes camunda-cloud/tasklist#1410

2021-11-17 22:54 UTC, akeller requested changes
Couple of small changes here.

Do you have other questions to add or are you looking to merge this with just the one?

2021-11-17 22:54 UTC, akeller commented on docs/components/tasklist/faq.md
> +title: FAQ
```suggestion
title: Tasklist FAQ
```

2021-11-17 22:54 UTC, akeller commented on docs/components/tasklist/faq.md
> +### Why my submit button is missing when I use Camunda Forms?
```suggestion
### Why is the submit button missing when I use Camunda Forms?
```

2021-11-18 09:29 UTC, vsgoulart commented
> Do you have other questions to add or are you looking to merge this with just the one?

@akeller I'll check with the team if they have anything else that they would like to include, I only created the FAQ section because a user was confused by this behaviour and I didn't know exactly where to put that information :sweat_smile:

2021-11-19 09:42 UTC, santanaluiz approved these changes

2021-11-19 09:48 UTC, vsgoulart commented
We didn't have anything else relevant to add so I'll just merge with this one @akeller

2021-11-19 17:52 UTC, akeller approved these changes

2021-11-19 17:52 UTC, merged