Updating recommended elasticsearch version
camunda-cloud/camunda-cloud-documentation pull request #505
Opened 2021-12-14 09:00 UTC by santanaluiz

Updating recommended elasticsearch version

NOTE: link says 404 but it is the link provided in here:
https://www.elastic.co/downloads/past-releases#elasticsearch
I am assuming they will fix it soon

Closes #404

2021-12-14 09:03 UTC, menski requested changes
I guess we should also update the versions on https://docs.camunda.io/docs/reference/supported-environments/

2021-12-14 09:03 UTC, menski commented on versioned_docs/version-1.0/components/tasklist/deployment/install-and-start.md
> +Tasklist is currently compatible with Elasticsearch 7.16.1. Download Elasticsearch [here](https://www.elastic.co/downloads/past-releases/elasticsearch-7-16-1).
as 1.0 is not supported anymore, I guess we don't have to update it here, wdyt?

2021-12-14 16:29 UTC, christinaausley approved these changes
Really appreciate you shifting the links to [here] rather than several words -- from a technical writing perspective this looks good to go.

2021-12-31 10:17 UTC, menski approved these changes

2021-12-31 10:17 UTC, menski commented on versioned_docs/version-1.0/components/operate/deployment/install-and-start.md
> +Operate is currently compatible with Elasticsearch 7.16.1. Download Elasticsearch [here](https://www.elastic.co/downloads/past-releases/elasticsearch-7-16-1).
I removed this change as we didn't updated 1.0 releases

2021-12-31 10:17 UTC, menski commented on versioned_docs/version-1.0/components/tasklist/deployment/install-and-start.md
> +Tasklist is currently compatible with Elasticsearch 7.16.1. Download Elasticsearch [here](https://www.elastic.co/downloads/past-releases/elasticsearch-7-16-1).
I removed this change as we didn't updated 1.0 releases

2021-12-31 10:27 UTC, merged