add dmn modeling page to web modeler docs
camunda-cloud/camunda-cloud-documentation pull request #747
Opened 2022-04-04 11:45 UTC by SebastianStamm

2022-04-04 12:53 UTC, CatalinaMoisuc commented
FYI @akeller I discussed with @MaxTru and he will change [this PR](https://github.com/camunda-cloud/camunda-cloud-documentation/pull/738) to make the guide under DMN generic as he did with [this one](https://github.com/camunda-cloud/camunda-cloud-documentation/pull/739).

I also looked into the [save and deploy](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/web-modeler-dmn/docs/components/modeler/web-modeler/save-and-deploy.md) page within the context of DMN and I think it looks fine and applies to both DMN and BPMN since we don't call them by name but simply "diagram".


So assuming we have a generic DMN page, how much content from [this page](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/web-modeler-dmn/docs/components/modeler/web-modeler/modeling-dmn.md) in the Web Modeler section we need? Wdyt @akeller ?

2022-04-04 18:54 UTC, akeller commented
> So assuming we have a generic DMN page for both Modelers, how much content from [this page](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/web-modeler-dmn/docs/components/modeler/web-modeler/modeling-dmn.md) in the Web Modeler section we need? Wdyt @akeller ?

I have not had a chance to go hands on with the modeling components, but if the actions for modeling DMN are identical (which is looks like they are), let's have one page to cover the experience in desktop and web modeler.

The only difference we may want to document is the auto-save feature on web modeler, but this could be done with a simple admonition/note.

2022-04-05 22:22 UTC, akeller commented
Let me know if you need more clarification from me here. I merged @MaxTru's other PRs.

2022-04-06 06:05 UTC, CatalinaMoisuc requested changes

2022-04-06 06:05 UTC, CatalinaMoisuc commented on docs/components/modeler/web-modeler/modeling-dmn.md
> +## Create new DMN decision requirement diagram
@SebastianStamm then let's move this one to `launch-cloud-modeler` and mention there that you can create DMN and BPMN.

2022-04-06 06:05 UTC, CatalinaMoisuc commented on docs/components/modeler/web-modeler/modeling-dmn.md
> +![Start Modeling](./img/dmn/main.png)
The rest should be covered as @akeller mentioned by @MaxTru's PR: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/738#pullrequestreview-932578226

2022-04-06 06:07 UTC, CatalinaMoisuc commented on docs/components/modeler/web-modeler/modeling-dmn.md
> +## Create new DMN decision requirement diagram
So essentially after this part is moved, we should remove the page with all the screenshots.

2022-04-06 06:08 UTC, CatalinaMoisuc commented
> > So assuming we have a generic DMN page for both Modelers, how much content from [this page](https://github.com/camunda-cloud/camunda-cloud-documentation/blob/web-modeler-dmn/docs/components/modeler/web-modeler/modeling-dmn.md) in the Web Modeler section we need? Wdyt @akeller ?
> 
> I have not had a chance to go hands on with the modeling components, but if the actions for modeling DMN are identical (which is looks like they are), let's have one page to cover the experience in desktop and web modeler.
> 
> The only difference we may want to document is the auto-save feature on web modeler, but this could be done with a simple admonition/note.

Thanks for clarifying @akeller. Then let's proceed like this. We only mention DMN  where needed in the existent documentation (i.e. create, import etc.) and we keep the common DMN modeling page that Max proposed.

2022-04-06 10:37 UTC, SebastianStamm commented
@CatalinaMoisuc I have removed the dedicated web-modeler DMN page together with the screenshots and adjusted the "Launch Web Modeler" page to include DMN and Forms as well as an updated screenshot. Please let me know if I need to make any other changes.

The failing CI is unrelated to the changes in this PR.

2022-04-06 11:46 UTC, CatalinaMoisuc approved these changes
lgtm.

2022-04-06 11:47 UTC, CatalinaMoisuc commented
@akeller do you have any idea about the broken links reported in [the build](https://github.com/camunda-cloud/camunda-cloud-documentation/runs/5848914161?check_suite_focus=true)?

2022-04-06 22:31 UTC, akeller commented
I'll take care of it @CatalinaMoisuc 😄

2022-04-06 22:53 UTC, akeller approved these changes
LGTM! And fixed the build issue by pulling in the latest release branch changes 😄

2022-04-06 22:54 UTC, merged